name: Go

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install dependencies
        run: go get -v -t -d ./...

      - name: Build-Macos
        run: GOOS=darwin GOARCH=amd64 go build -o ./dist/fs_macOS_AMD64

      - name: Build-Macos-Arm64
        run: GOOS=darwin GOARCH=arm64 go build -o ./dist/fs_macOS_Apple_Silicon

      - name: Build-Windows-x64
        run: GOOS=windows GOARCH=amd64 go build -o ./dist/fs_Windows_AMD64.exe

      - name: Build-Windows-AMR64
        run: GOOS=windows GOARCH=arm64 go build -o ./dist/fs_Windows_ARM64.exe

      - name: Build-Linux-x64
        run: GOOS=linux GOARCH=amd64 go build -o ./dist/fs_Linux_AMD64

      - name: Build-Linux-AMR64
        run: GOOS=linux GOARCH=arm64 go build -o ./dist/fs_Linux_ARM64

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./dist/*